name: inventory_management_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # Firebase Core (required for Firebase initialization)
  firebase_core: ^3.6.0

  # Cloud Firestore (for Firestore database integration)
  cloud_firestore: ^5.4.4

  # Cupertino Icons for iOS style icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended linting rules
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
